version: '3.8'

services:
  # Autism React Application
  autism:
    build:
      context: ./autism
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./autism:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5174
    networks:
      - elm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5174/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # People Analytics React Application
  people-analytics:
    build:
      context: ./peopleAnalytics
      dockerfile: Dockerfile
    ports:
      - "5175:5175"
    volumes:
      - ./peopleAnalytics:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5175
    networks:
      - elm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5175/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Elmhub React Application
  elmhub:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - elm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Sage React Application
  sage:
    build:
      context: ./sage
      dockerfile: Dockerfile
    ports:
      - "5176:5176"
    volumes:
      - ./sage:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5176
    networks:
      - elm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5176/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - elm-network
    depends_on:
      - autism
      - people-analytics
      - sage
      - elmhub

networks:
  elm-network:
    driver: bridge
